[package]
name = "task-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
thiserror = "2.0.12"
async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.4"
